import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Input } from "@material-tailwind/react";
import { useState } from "react";
import generateAction from './api/generate'
import React from "react";
import axios from 'axios';

export default function Home() {
  
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className="container mx-auto bg-gray-200 rounded-xl shadow border p-8 m-10">
        <h1 className="text-gray-700 text-lg text-center" >Chatter App</h1>
      </div>
      <Question />
    </>
  );
}

function Question() {
  const [val, setVal] = useState("");
  const [messages, setMessages] = useState<string[]>([]);
  const [apiOutput, setApiOutput] = useState('')
  const [isGenerating, setIsGenerating] = useState(false)

  const callGenerateEndpoint = async () => {
    setIsGenerating(true);
  
    console.log("Calling OpenAI...")
    
    try {
      const response = await axios.get('/api/hello');
      console.log(response);
    } catch (error) {
      console.log("calling hello");
    }

    try {
      
      const response = await axios.post('/api/generate', {
        userInput: val,
      });
  
      const data = await response.data;
      const { output } = data;
      console.log(data)
    
      console.log("OpenAI replied...", output.text);
      setMessages((prevMessages) => [...prevMessages, "Bot: " + output.text]);
      setApiOutput(output.text);
    } catch (error) {
      console.log("Error calling OpenAI API:", error);
    } finally {
      setIsGenerating(false);
    }
  }

  const click = () => {
    setMessages((prevMessages) => [...prevMessages, "You: " + val]);
    setVal("");
    callGenerateEndpoint();
  }

  const change = (event: any) => {
    setVal(event.target.value);
  }

  return (
    <div className="container mx-auto">
      <p>
        ask lex a question
      </p>
      <Input onChange={change}
        value={val} />
      <button onClick={click} className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
        Click me!
      </button>
      <div>
        {messages.length > 0 && (
          <p>
            Messages: <br />
            {messages.map((element, index) => (
              <p key={index}>{element}</p>
            ))}
          </p>
        )}
      </div>
    </div>
  );
}